@echo off
echo Stopping any running dev servers...
taskkill /f /im node.exe 2>nul
echo Clearing cache...
rmdir /s /q node_modules 2>nul
del package-lock.json 2>nul
echo Installing dependencies...
npm install
echo Starting development server...
npm run dev
